import asyncio
import contextlib
import json
import operator
import os
import uuid
from pathlib import Path
from typing import Annotated, Any, Optional, TypedDict

from dotenv import load_dotenv
from langchain_core.messages import AnyMessage, HumanMessage, SystemMessage
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_groq import ChatGroq
from langgraph.checkpoint.memory import MemorySaver
from langgraph.checkpoint.postgres import PostgresSaver
from langgraph.graph import END, START, StateGraph
from langgraph.types import Command, interrupt
from mcp_client import (
    tavily_mcp_search,
    weather_mcp_search,
    forecast_mcp_search,
    aviation_get_flights,
    extract_iata_codes,
)


load_dotenv(Path(__file__).resolve().parent / ".env")


class TravelState(TypedDict, total=False):
    messages: Annotated[list[AnyMessage], operator.add]
    user_query: str
    guardrail_allowed: bool
    guardrail_reason: str
    selected_agents: list[str]
    trip_constraints: dict[str, Any]
    supervisor_reasoning: str
    intent_mode: str  # "trip_planning" or "direct_query"
    origin_currency: str
    destination_currency: str
    exchange_rate: float
    flight_results: str
    hotel_results: str
    weather_results: str
    budget_results: str
    itinerary: str
    approval_request: str
    approved: Optional[bool]
    human_feedback: Optional[str]
    final_response: str
    llm_calls: int


SPECIALIST_NAMES = {
    "flight_agent",
    "hotel_agent",
    "weather_agent",
    "budget_agent",
}


def get_llm() -> ChatGroq:
    api_key = os.getenv("GROQ_API_KEY") or os.getenv("GROQ_API_KEY_FALLBACK")
    if not api_key:
        raise ValueError("Neither GROQ_API_KEY nor GROQ_API_KEY_FALLBACK is set in the environment")

    model_name = os.getenv("GROQ_MODEL", "openai/gpt-oss-120b")

    return ChatGroq(
        model=model_name,
        groq_api_key=api_key,
        temperature=0.0,
    )


def _llm_text(system_prompt: str, user_prompt: str) -> str:
    import time
    llm = get_llm()
    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=user_prompt)
    ]
    max_retries = 4
    delay = 15  # start with 15 seconds to allow TPM decay
    
    for attempt in range(max_retries):
        try:
            res = llm.invoke(messages)
            return res.content
        except Exception as e:
            error_str = str(e).lower()
            # Catch rate limit, TPM/RPM limits, HTTP 429, or HTTP 413 token-limit errors
            if any(term in error_str for term in ("rate_limit", "tpm", "tokens per minute", "too large", "overloaded", "413", "429")):
                if attempt < max_retries - 1:
                    print(f"⚠️ Groq rate/TPM limit hit. Sleeping {delay}s before retry (Attempt {attempt+1}/{max_retries})...")
                    time.sleep(delay)
                    delay *= 2
                    continue
            raise e


def _json_from_llm(text: str) -> dict[str, Any]:
    # Strip <think>...</think> blocks if generated by reasoning models
    if "<think>" in text and "</think>" in text:
        parts = text.split("</think>", 1)
        text = parts[1]

    text = text.strip()
    if not text:
        return {}

    start = text.find("{")
    end = text.rfind("}")

    if start == -1 or end == -1 or end < start:
        return {}

    json_str = text[start : end + 1]

    try:
        return json.loads(json_str)
    except json.JSONDecodeError:
        return {}


def _empty_constraints() -> dict[str, Any]:
    return {
        "destination": "",
        "origin": "",
        "duration": "",
        "budget": "",
        "travel_style": "",
    }


CURRENCY_MAP = {
    "london": "GBP",
    "uk": "GBP",
    "united kingdom": "GBP",
    "paris": "EUR",
    "france": "EUR",
    "tokyo": "JPY",
    "japan": "JPY",
    "india": "INR",
    "delhi": "INR",
    "mumbai": "INR",
    "bangalore": "INR",
    "new york": "USD",
    "america": "USD",
    "united states": "USD",
    "usa": "USD",
    "canada": "CAD",
    "toronto": "CAD",
    "australia": "AUD",
    "sydney": "AUD",
    "melbourne": "AUD",
    "germany": "EUR",
    "berlin": "EUR",
    "italy": "EUR",
    "rome": "EUR",
    "spain": "EUR",
    "madrid": "EUR",
    "singapore": "SGD",
    "dubai": "AED",
    "uae": "AED",
}

def get_currency_for_location(location: str) -> str:
    if not location:
        return "USD"
    loc_lower = location.lower().strip()
    
    # Check static map
    for key, code in CURRENCY_MAP.items():
        if key in loc_lower:
            return code
            
    # Fallback to LLM
    try:
        res = _llm_text(
            "You are a currency resolver. Based on the given city or country, respond with ONLY its standard ISO 4217 three-letter currency code (e.g. USD, EUR, GBP, JPY, INR). Do not include any formatting, punctuation, or other text.",
            f"Location: {location}"
        )
        code = res.strip().upper()
        if len(code) == 3 and code.isalpha():
            return code
    except Exception:
        pass
        
    return "USD"


def get_exchange_rate(from_currency: str, to_currency: str) -> float:
    import urllib.request
    
    api_key = os.getenv("EXCHANGE_RATE_API_KEY")
    if not api_key:
        print("⚠️ Warning: EXCHANGE_RATE_API_KEY is not set in the environment.")
        return 1.0
        
    if from_currency.upper() == to_currency.upper():
        return 1.0
        
    url = f"https://v6.exchangerate-api.com/v6/{api_key}/latest/{to_currency.upper()}"
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req, timeout=5) as response:
            data = json.loads(response.read().decode())
            if data.get("result") == "success":
                rates = data.get("conversion_rates", {})
                rate = rates.get(from_currency.upper())
                if rate is not None:
                    print(f"📊 Live exchange rate: 1 {to_currency.upper()} = {rate} {from_currency.upper()}")
                    return float(rate)
    except Exception as e:
        print(f"⚠️ Error fetching exchange rate from API: {e}")
        
    return 1.0


def _get_user_query(state: TravelState) -> str:
    user_query = state.get("user_query", "")

    if user_query:
        return user_query

    for message in reversed(state.get("messages", [])):
        if isinstance(message, HumanMessage):
            content = message.content
            if isinstance(content, str):
                return content

        if hasattr(message, "type") and message.type == "human":
            content = getattr(message, "content", "")
            if isinstance(content, str):
                return content

        if isinstance(message, dict) and message.get("type") == "human":
            content = message.get("content", "")
            if isinstance(content, str):
                return content

    return ""


def supervisor_node(state: TravelState) -> dict[str, Any]:
    user_query = _get_user_query(state)

    guardrail_system = (
        "You are a strict travel safety guardrail. Your task is to determine whether "
        "the user query is strictly travel-related, such as planning a trip, booking flights/hotels, "
        "checking weather, estimating budgets, or listing travel itineraries/activities.\n"
        "Crucially, you must BLOCK:\n"
        "- General tutorials or 'how-to' guides (e.g., learning how to ride a bike, swim, code, cook, or speak a language), "
        "even if the user claims it is 'during the trip' or 'for travel'.\n"
        "- General knowledge, jokes, programming, math, essays, or off-topic conversational fillers.\n"
        "If the query is strictly travel-related, respond with {\"allowed\": true, \"reason\": \"Explanation\"}.\n"
        "If it is not, respond with {\"allowed\": false, \"reason\": \"Explanation why it is blocked\"}.\n"
        "Respond ONLY with valid JSON in this format: "
        '{"allowed": true, "reason": "..."}'
    )

    guardrail_result = _llm_text(
        guardrail_system,
        f"Query: {user_query}",
    )
    guardrail_json = _json_from_llm(guardrail_result)

    allowed = bool(guardrail_json.get("allowed", False))
    reason = guardrail_json.get(
        "reason",
        "Query is not travel-related.",
    )

    if not allowed:
        return {
            "user_query": user_query,
            "guardrail_allowed": False,
            "guardrail_reason": reason,
            "final_response": reason,
            "llm_calls": state.get("llm_calls", 0) + 1,
        }

    supervisor_system = (
        "You are a travel coordinator supervisor. Analyze the user's travel request.\n"
        "First, classify the user's intent as either:\n"
        "- \"trip_planning\": if they request a multi-day itinerary or trip plan.\n"
        "- \"direct_query\": if they only ask a single-topic question, e.g., checking weather at a destination, searching flight options between airports, or listing hotel options, and do NOT request a multi-day itinerary.\n\n"
        "Select only the specialist agents actually required. Available specialists are:\n"
        "- flight_agent: routes, ticket information, schedules\n"
        "- hotel_agent: accommodation and locations\n"
        "- weather_agent: destination weather conditions\n"
        "- budget_agent: total trip cost estimation\n\n"
        "Extract these trip constraints: destination, origin, duration, budget, travel_style.\n"
        "Respond ONLY with valid JSON in exactly this structure:\n"
        '{"intent_mode": "trip_planning", '
        '"selected_agents": ["flight_agent"], '
        '"trip_constraints": {"destination": "...", "origin": "...", '
        '"duration": "...", "budget": "...", "travel_style": "..."}, '
        '"reasoning": "..."}'
    )

    supervisor_result = _llm_text(
        supervisor_system,
        f"Query: {user_query}",
    )
    supervisor_json = _json_from_llm(supervisor_result)

    selected_agents = [
        agent
        for agent in supervisor_json.get("selected_agents", [])
        if agent in SPECIALIST_NAMES
    ]

    intent_mode = supervisor_json.get("intent_mode", "trip_planning")
    if intent_mode not in ("trip_planning", "direct_query"):
        intent_mode = "trip_planning"

    constraints = supervisor_json.get("trip_constraints")
    if not isinstance(constraints, dict):
        constraints = _empty_constraints()

    normalized_constraints = _empty_constraints()
    normalized_constraints.update(constraints)

    origin_currency = get_currency_for_location(normalized_constraints.get("origin", ""))
    destination_currency = get_currency_for_location(normalized_constraints.get("destination", ""))
    exchange_rate = get_exchange_rate(origin_currency, destination_currency)

    return {
        "user_query": user_query,
        "guardrail_allowed": True,
        "guardrail_reason": "",
        "selected_agents": selected_agents,
        "trip_constraints": normalized_constraints,
        "supervisor_reasoning": supervisor_json.get("reasoning", ""),
        "intent_mode": intent_mode,
        "origin_currency": origin_currency,
        "destination_currency": destination_currency,
        "exchange_rate": exchange_rate,
        "llm_calls": state.get("llm_calls", 0) + 2,
    }


def flight_node(state: TravelState) -> dict[str, Any]:
    constraints = state.get("trip_constraints", {})
    result = _llm_text(
        "You are a flight specialist agent. Suggest suitable flight options, "
        "airline carriers, routes, schedules, and approximate price ranges. "
        "Clearly state that prices and schedules are estimates unless real-time "
        "flight data is available. Return a clear Markdown summary.",
        f"Constraints: {json.dumps(constraints, ensure_ascii=False)}",
    )
    return {
        "flight_results": result,
        "llm_calls": state.get("llm_calls", 0) + 1,
    }


def hotel_node(state: TravelState) -> dict[str, Any]:
    constraints = state.get("trip_constraints", {})
    result = _llm_text(
        "You are a hotel specialist agent. Suggest suitable accommodation "
        "types, neighborhoods, and hotel recommendations based on the user's "
        "constraints. Clearly state that availability and prices must be verified. "
        "Return a clear Markdown summary.",
        f"Constraints: {json.dumps(constraints, ensure_ascii=False)}",
    )
    return {
        "hotel_results": result,
        "llm_calls": state.get("llm_calls", 0) + 1,
    }


def weather_node(state: TravelState) -> dict[str, Any]:
    constraints = state.get("trip_constraints", {})
    result = _llm_text(
        "You are a weather specialist agent. Provide useful expected weather "
        "information for the destination and travel period. Clearly state that "
        "future weather should be verified with a live weather service. Return "
        "a clear Markdown summary.",
        f"Constraints: {json.dumps(constraints, ensure_ascii=False)}",
    )
    return {
        "weather_results": result,
        "llm_calls": state.get("llm_calls", 0) + 1,
    }


def budget_node(state: TravelState) -> dict[str, Any]:
    constraints = state.get("trip_constraints", {})
    result = _llm_text(
        "You are a travel budget specialist. Estimate the total trip cost from "
        "the supplied constraints. Include transportation, accommodation, food, "
        "activities, local transport, and a contingency when appropriate. Clearly "
        "label estimates and assumptions. Return a clear Markdown summary.",
        f"Constraints: {json.dumps(constraints, ensure_ascii=False)}",
    )
    return {
        "budget_results": result,
        "llm_calls": state.get("llm_calls", 0) + 1,
    }


def itinerary_node(state: TravelState) -> dict[str, Any]:
    user_query = state.get("user_query", "")
    constraints = state.get("trip_constraints", {})
    feedback = state.get("human_feedback", "")
    origin_currency = state.get("origin_currency", "USD")
    destination_currency = state.get("destination_currency", "USD")
    exchange_rate = state.get("exchange_rate", 1.0)

    prompt_content = f"""
User Request:
{user_query}

Trip Constraints:
{json.dumps(constraints, ensure_ascii=False)}

Flight Options:
{state.get("flight_results", "Not requested")}

Hotel Options:
{state.get("hotel_results", "Not requested")}

Weather Details:
{state.get("weather_results", "Not requested")}

Budget Estimate:
{state.get("budget_results", "Not requested")}
"""

    print(f"📝 [Itinerary Agent] Synthesizing day-by-day plan. Human feedback received: '{feedback}'")

    if feedback:
        prompt_content += (
            f"\n⚠️ CRITICAL REVISION REQUEST FROM HUMAN ADVISOR:\n"
            f"Please revise the previous draft itinerary strictly incorporating the following feedback:\n"
            f"\"{feedback}\"\n\n"
            f"You MUST adjust the hotels, flights, budget, schedules, or other elements of the travel plan "
            f"to satisfy this request."
        )

    system_prompt = (
        "You are a master travel planner. Synthesize the provided information into "
        "a cohesive day-by-day itinerary. Use detailed Markdown, clean headings, "
        "bold text, bullet lists, and emojis. Do not claim that an external booking "
        "or weather API was checked unless the input explicitly contains such data.\n"
        "CRITICAL INSTRUCTION: The traveler's origin currency is '{origin_currency}' and the destination currency is '{destination_currency}'. "
        "You MUST display all monetary values, price ranges, daily costs, and the final budget breakdown table STRICTLY in the traveler's home currency '{origin_currency}' (using standard symbols like $, £, €, ₹). "
        "Do NOT use the destination currency '{destination_currency}' for any prices. "
        "The conversion rate is: 1 {destination_currency} = {exchange_rate} {origin_currency}.\n\n"
        "Separate the response using exactly these boundaries:\n"
        "--- ITINERARY_START ---\n"
        "[Detailed Markdown Itinerary]\n"
        "--- SUMMARY_START ---\n"
        "[Short Summary for Approval]"
    )
    system_prompt = (
        system_prompt
        .replace("{origin_currency}", origin_currency)
        .replace("{destination_currency}", destination_currency)
        .replace("{exchange_rate}", str(exchange_rate))
    )

    result = _llm_text(system_prompt, prompt_content)

    itinerary = result.strip()
    summary = "Draft travel itinerary prepared for approval."

    if "--- SUMMARY_START ---" in result:
        itinerary_part, summary_part = result.split(
            "--- SUMMARY_START ---", 1
        )
        itinerary = itinerary_part.replace(
            "--- ITINERARY_START ---", ""
        ).strip()
        summary = summary_part.strip()
    elif "--- ITINERARY_START ---" in result:
        itinerary = result.replace(
            "--- ITINERARY_START ---", ""
        ).strip()

    return {
        "itinerary": itinerary,
        "approval_request": summary,
        "approved": None,
        "human_feedback": None,
        "llm_calls": state.get("llm_calls", 0) + 1,
    }


def hitl_node(state: TravelState) -> dict[str, Any]:
    if state.get("approved") is True:
        return {}

    resume_data = interrupt(
        {
            "summary": state.get(
                "approval_request",
                "Review the travel plan.",
            ),
            "itinerary": state.get("itinerary", ""),
            "user_query": state.get("user_query", ""),
            "trip_constraints": state.get("trip_constraints", {}),
        }
    )

    if not isinstance(resume_data, dict):
        resume_data = {}

    return {
        "approved": bool(resume_data.get("approved", False)),
        "human_feedback": str(resume_data.get("feedback", "")),
    }


def finalize_node(state: TravelState) -> dict[str, Any]:
    return {
        "final_response": state.get("itinerary", ""),
        "approved": True,
    }


def route_after_supervisor(state: TravelState) -> str:
    if not state.get("guardrail_allowed", True):
        return "end"

    agents = state.get("selected_agents", [])
    if not agents:
        return "itinerary_agent"

    # The specialist coordinator runs only the selected specialists and creates
    # a single synchronization point before itinerary generation.
    return "specialists"


def specialists_node(state: TravelState) -> dict[str, Any]:
    """Run the selected specialist agents sequentially as a single fanning-in point.

    This avoids triggering itinerary_node multiple times when the supervisor
    selects more than one specialist.
    """
    constraints = state.get("trip_constraints", {})
    selected = state.get("selected_agents", [])
    updates: dict[str, Any] = {}
    llm_calls = state.get("llm_calls", 0)

    # 1. Flight Agent
    if "flight_agent" in selected:
        origin = constraints.get("origin", "")
        destination = constraints.get("destination", "")
        flight_data = "No flights retrieved."
        
        if origin and destination:
            iata_codes = extract_iata_codes(origin, destination)
            origin_iata = iata_codes.get("origin_iata")
            dest_iata = iata_codes.get("destination_iata")
            if origin_iata and dest_iata:
                try:
                    flight_data = asyncio.run(aviation_get_flights(origin_iata, dest_iata))
                except Exception as e:
                    flight_data = f"Error fetching flight data: {e}"
        
        system_prompt = (
            "You are a flight specialist agent. Based on these constraints: {constraints} and the real-time flight details: {flight_data}, suggest suitable flight options, airline carriers, routes, and price ranges. Keep your response extremely concise (max 200 words) and output a clear markdown summary."
        )
        system_prompt = system_prompt.replace("{constraints}", json.dumps(constraints, ensure_ascii=False)).replace("{flight_data}", flight_data)
        
        result = _llm_text(
            system_prompt,
            f"Constraints: {json.dumps(constraints, ensure_ascii=False)}"
        )
        updates["flight_results"] = result
        llm_calls += 2

    # 2. Hotel Agent
    if "hotel_agent" in selected:
        destination = constraints.get("destination", "")
        hotel_data = "No hotel search data retrieved."
        if destination:
            try:
                hotel_data = asyncio.run(tavily_mcp_search(f"best hotels and neighborhoods in {destination}"))
            except Exception as e:
                hotel_data = f"Error fetching hotel data: {e}"
                
        system_prompt = (
            "You are a hotel specialist agent. Based on these constraints: {constraints} and the Tavily search results: {hotel_data}, suggest suitable accommodation options, neighborhoods, and hotel recommendations. Keep your response extremely concise (max 200 words) and output a clear markdown summary."
        )
        system_prompt = system_prompt.replace("{constraints}", json.dumps(constraints, ensure_ascii=False)).replace("{hotel_data}", hotel_data)
        
        result = _llm_text(
            system_prompt,
            f"Constraints: {json.dumps(constraints, ensure_ascii=False)}"
        )
        updates["hotel_results"] = result
        llm_calls += 1

    # 3. Weather Agent
    if "weather_agent" in selected:
        destination = constraints.get("destination", "")
        weather_data = "No weather forecast retrieved."
        if destination:
            try:
                weather_data = asyncio.run(forecast_mcp_search(destination, days=3))
            except Exception as e:
                weather_data = f"Error fetching weather forecast: {e}"
                
        system_prompt = (
            "You are a weather specialist agent. Based on these constraints: {constraints} and the weather forecast: {weather_data}, provide useful expected weather information for the destination. Keep your response extremely concise (max 150 words) and output a clear markdown summary."
        )
        system_prompt = system_prompt.replace("{constraints}", json.dumps(constraints, ensure_ascii=False)).replace("{weather_data}", weather_data)
        
        result = _llm_text(
            system_prompt,
            f"Constraints: {json.dumps(constraints, ensure_ascii=False)}"
        )
        updates["weather_results"] = result
        llm_calls += 1

    # 4. Budget Agent
    if "budget_agent" in selected:
        destination = constraints.get("destination", "")
        budget_data = "No budget search data retrieved."
        if destination:
            try:
                budget_data = asyncio.run(tavily_mcp_search(f"typical daily budget activities and local transport costs in {destination}"))
            except Exception as e:
                budget_data = f"Error fetching budget data: {e}"
                
        origin_currency = state.get("origin_currency", "USD")
        destination_currency = state.get("destination_currency", "USD")
        exchange_rate = state.get("exchange_rate", 1.0)
        
        system_prompt = (
            "You are a travel budget specialist. Based on these constraints: {constraints} and the typical costs context: {budget_data}, estimate the total trip cost. Include transportation, accommodation, activities, local transport, and contingency.\n"
            "CRITICAL INSTRUCTION: The traveler's origin is '{origin}' (Currency: {origin_currency}) and the destination is '{destination}' (Currency: {destination_currency}). "
            "You MUST present the entire budget estimation, daily breakdown, and item costs STRICTLY in the traveler's home currency '{origin_currency}' (symbol/format). "
            "Use the conversion rate: 1 {destination_currency} = {exchange_rate} {origin_currency} to convert any local destination prices into {origin_currency} before summarizing them.\n"
            "Keep your response extremely concise (max 180 words) and output a clear markdown summary."
        )
        system_prompt = (
            system_prompt
            .replace("{constraints}", json.dumps(constraints, ensure_ascii=False))
            .replace("{budget_data}", budget_data)
            .replace("{origin}", constraints.get("origin", ""))
            .replace("{destination}", constraints.get("destination", ""))
            .replace("{origin_currency}", origin_currency)
            .replace("{destination_currency}", destination_currency)
            .replace("{exchange_rate}", str(exchange_rate))
        )
        
        result = _llm_text(
            system_prompt,
            f"Constraints: {json.dumps(constraints, ensure_ascii=False)}"
        )
        updates["budget_results"] = result
        llm_calls += 1

    updates["llm_calls"] = llm_calls
    return updates


def direct_response_node(state: TravelState) -> dict[str, Any]:
    selected = state.get("selected_agents", [])
    results = []

    # Map selected agents to their respective results fields
    if "flight_agent" in selected and state.get("flight_results"):
        results.append(f"### ✈️ Flight Recommendations\n{state['flight_results']}")
    if "hotel_agent" in selected and state.get("hotel_results"):
        results.append(f"### 🏨 Accommodation Options\n{state['hotel_results']}")
    if "weather_agent" in selected and state.get("weather_results"):
        results.append(f"### 🌤️ Weather Forecast\n{state['weather_results']}")
    if "budget_agent" in selected and state.get("budget_results"):
        results.append(f"### 💰 Budget & Cost Analysis\n{state['budget_results']}")

    if results:
        final_text = "\n\n---\n\n".join(results)
    else:
        final_text = "No results compiled for your direct query."

    return {
        "final_response": final_text,
        "approved": True
    }


def route_after_specialists(state: TravelState) -> str:
    if state.get("intent_mode") == "direct_query":
        return "direct_response"
    return "itinerary_agent"


def route_after_hitl(state: TravelState) -> str:
    if state.get("approved") is True:
        return "finalize"
    return "itinerary_agent"


workflow = StateGraph(TravelState)

workflow.add_node("supervisor_agent", supervisor_node)
workflow.add_node("specialists", specialists_node)
workflow.add_node("direct_response", direct_response_node)
workflow.add_node("itinerary_agent", itinerary_node)
workflow.add_node("hitl_approval", hitl_node)
workflow.add_node("finalize", finalize_node)

workflow.add_edge(START, "supervisor_agent")

workflow.add_conditional_edges(
    "supervisor_agent",
    route_after_supervisor,
    {
        "specialists": "specialists",
        "itinerary_agent": "itinerary_agent",
        "end": END,
    },
)

workflow.add_conditional_edges(
    "specialists",
    route_after_specialists,
    {
        "direct_response": "direct_response",
        "itinerary_agent": "itinerary_agent"
    }
)
workflow.add_edge("direct_response", END)
workflow.add_edge("itinerary_agent", "hitl_approval")

workflow.add_conditional_edges(
    "hitl_approval",
    route_after_hitl,
    {
        "finalize": "finalize",
        "itinerary_agent": "itinerary_agent",
    },
)

workflow.add_edge("finalize", END)


_global_memory_saver = MemorySaver()


@contextlib.contextmanager
def get_graph():
    database_url = os.getenv("DATABASE_URL")
    use_postgres = False

    if database_url:
        try:
            with PostgresSaver.from_conn_string(database_url) as saver:
                saver.setup()
            use_postgres = True
        except Exception as e:
            print(f"⚠️ PostgresSaver connection failed: {e}. Falling back to MemorySaver checkpointer.")

    if use_postgres:
        with PostgresSaver.from_conn_string(database_url) as saver:
            yield workflow.compile(checkpointer=saver)
    else:
        yield workflow.compile(checkpointer=_global_memory_saver)


def run_travel_agent(
    message: str,
    thread_id: Optional[str] = None,
) -> dict[str, Any]:
    if not thread_id:
        thread_id = str(uuid.uuid4())

    config = {"configurable": {"thread_id": thread_id}}

    try:
        with get_graph() as graph:
            graph.invoke(
                {
                    "user_query": message,
                    "messages": [HumanMessage(content=message)],
                    "llm_calls": 0,
                },
                config,
            )

            state = graph.get_state(config)

            if state.values.get("guardrail_allowed") is False:
                return {
                    "thread_id": thread_id,
                    "status": "blocked",
                    "content": state.values.get(
                        "final_response",
                        "Query blocked by guardrail.",
                    ),
                    "awaiting_approval": False,
                    "agents_run": ["supervisor_agent"],
                }

            is_awaiting = bool(
                state.next and "hitl_approval" in state.next
            )

            if is_awaiting:
                return {
                    "thread_id": thread_id,
                    "status": "awaiting_approval",
                    "content": state.values.get(
                        "approval_request",
                        "Review travel plan",
                    ),
                    "itinerary": state.values.get("itinerary", ""),
                    "awaiting_approval": True,
                    "agents_run": (
                        ["supervisor_agent"]
                        + state.values.get("selected_agents", [])
                        + ["itinerary_agent"]
                    ),
                }

            return {
                "thread_id": thread_id,
                "status": "completed",
                "content": state.values.get("final_response", ""),
                "awaiting_approval": False,
                "agents_run": (
                    ["supervisor_agent"]
                    + state.values.get("selected_agents", [])
                    + (
                        [] if state.values.get("intent_mode") == "direct_query"
                        else ["itinerary_agent", "finalize"]
                    )
                ),
            }
    except Exception as e:
        error_msg = str(e).lower()
        if any(term in error_msg for term in ("nodename nor servname", "gai_error", "connection refused", "timeout", "offline")):
            return {
                "thread_id": thread_id,
                "status": "blocked",
                "content": "⚠️ Network Offline or Host Resolution Error. Please verify your internet connection and check if Groq/Supabase is reachable.",
                "awaiting_approval": False,
                "agents_run": []
            }
        raise e


def resume_travel_agent(
    thread_id: str,
    approved: bool,
    feedback: str = "",
) -> dict[str, Any]:
    config = {"configurable": {"thread_id": thread_id}}

    print(f"🔄 [HITL Resume] Resuming thread {thread_id} | approved={approved} | feedback='{feedback}'")

    try:
        with get_graph() as graph:
            graph.invoke(
                Command(
                    resume={
                        "approved": approved,
                        "feedback": feedback,
                    }
                ),
                config,
            )

            state = graph.get_state(config)

            is_awaiting = bool(
                state.next and "hitl_approval" in state.next
            )

            if is_awaiting:
                return {
                    "thread_id": thread_id,
                    "status": "awaiting_approval",
                    "content": state.values.get(
                        "approval_request",
                        "Review travel plan",
                    ),
                    "itinerary": state.values.get("itinerary", ""),
                    "awaiting_approval": True,
                    "agents_run": ["itinerary_agent"],
                }

            return {
                "thread_id": thread_id,
                "status": "completed",
                "content": state.values.get("final_response", ""),
                "awaiting_approval": False,
                "agents_run": ["finalize"],
            }
    except Exception as e:
        error_msg = str(e).lower()
        if any(term in error_msg for term in ("nodename nor servname", "gai_error", "connection refused", "timeout", "offline")):
            return {
                "thread_id": thread_id,
                "status": "blocked",
                "content": "⚠️ Network Offline or Host Resolution Error. Please verify your internet connection and check if Groq/Supabase is reachable.",
                "awaiting_approval": False,
                "agents_run": []
            }
        raise e
